foodie/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("sandbox/", include("sandbox.urls")),
    path("", include("foodie_app.urls")),
    path("recipes/", include("recipes.urls")),
    path("comments/", include("comments.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from recipes import views


app_name = "recipes"

router = DefaultRouter()
router.register(r"recipes", views.RecipeViewSet, basename="recipe")

urlpatterns = [
    path("", views.recipes, name="index"),
    path("<int:recipe_id>", views.recipe_detail, name="recipe_detail"),
    path(
        "<int:recipe_id>/toggle_favorite", views.toggle_favorite, name="toggle_favorite"
    ),
    path("my-favorites/", views.favorite_recipes, name="favorite_recipes"),
    path("search/", views.search_results, name="search_results"),
    path("<int:recipe_id>/delete/", views.delete_recipe, name="delete_recipe"),
    path("<int:recipe_id>/edit/", views.edit_recipe, name="edit_recipe"),
    path("api/", include(router.urls)),
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from foodie_app.models import Category


# Create your models here.
class Recipe(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    ingredients = models.TextField()
    directions = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, related_name="recipes"
    )
    image = models.ImageField(upload_to="recipe_images/", null=True, blank=True)
    favorited_by = models.ManyToManyField(User, related_name="favorite_recipes", blank=True)
    
    def get_absolute_url(self):
        return reverse("recipes:recipe_detail", args=[str(self.id)])

    def __str__(self):
        return self.name

recipes/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField(
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search recipes...", "class": "form-control mr-sm-2"}
        ),
    )

recipes/views.py
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from comments.forms import CommentForm
from foodie_app.forms import RecipeForm
from recipes.serializers import RecipeSerializer
from .models import Recipe
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from rest_framework import viewsets


def recipes(request):

    recipes = Recipe.objects.all().order_by("-date_added")
    context = {"recipes": recipes}

    return render(request, "recipes/recipes.html", context)


def recipe_detail(request, recipe_id):

    # recipe = Recipe.objects.get(id=recipe_id)
    recipe = get_object_or_404(Recipe, id=recipe_id)
    comments = recipe.comments.all()

    new_comment = None

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.recipe = recipe
            new_comment.user = request.user
            new_comment.save()
            return redirect(
                recipe.get_absolute_url()
            )  # Redirect to the same recipe page - refresh
    else:
        comment_form = CommentForm()

    context = {"recipe": recipe, "comments": comments, "comment_form": comment_form}
    return render(request, "recipes/recipe.html", context)


@login_required
def toggle_favorite(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)

    if request.user in recipe.favorited_by.all():
        recipe.favorited_by.remove(request.user)
    else:
        recipe.favorited_by.add(request.user)
    return redirect("recipes:recipe_detail", recipe_id=recipe_id)


@login_required
def favorite_recipes(request):
    user = request.user
    favorites = user.favorite_recipes.all()
    context = {"recipes": favorites}
    return render(request, "recipes/favorite_recipes.html", context)


def search_results(request):
    query = request.GET.get("query", "")

    results = (
        Recipe.objects.filter(
            Q(name__icontains=query)
            | Q(description__icontains=query)
            | Q(ingredients__icontains=query)
            | Q(directions__icontains=query)
            | Q(category__name__icontains=query)
        ).distinct()
        if query
        else []
    )
    # avoid duplicate results
    # seen_ids = set()
    # unique_results = []
    # for result in results:
    #     if result.id not in seen_ids:
    #         unique_results.append(result)
    #         seen_ids.add(result.id)

    # else:
    #     unique_results = []

    # results = Recipe.objects.filter(name__icontains=query) if query else []

    context = {"query": query, "results": results}
    return render(request, "recipes/search_results.html", context)


@login_required
def delete_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)

    # check if the current user is the owner of the recipe or a superuser
    if not request.user == recipe.user and not request.user.is_superuser:
        return HttpResponseForbidden()

    if request.method == "POST":
        recipe.delete()
        return redirect("recipes:index")

    context = {"recipe": recipe}
    return render(request, "recipes/recipe_confirmation_delete.html", context)


@login_required
def edit_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)

    if not request.user == recipe.user and not request.user.is_superuser:
        return HttpResponse("Not allowed.")
        # return HttpResponseForbidden()

    if request.method == "POST":
        form = RecipeForm(request.POST, request.FILES, instance=recipe)
        if form.is_valid():
            form.save()
            return redirect("recipes:recipe_detail", recipe_id=recipe.id)
    else:
        form = RecipeForm(instance=recipe)

    context = {"form": form, "recipe": recipe}
    return render(request, "recipes/recipe_form.html", context)


class RecipeViewSet(viewsets.ModelViewSet):
    queryset = Recipe.objects.all()
    serializer_class = RecipeSerializer

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

recipes/templates/recipes/favorite_recipes.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block page_header %}
    <h3>My Cookbook</h3>
{% endblock page_header %}
{% block content %}
    {% if recipes.exists %}
        <div>
            {% for recipe in recipes %}
                <div class="card mb-3 mx-auto" style="max-width: 540px;">
                    <div class="row g-0">
                        <div class="col-md-4 d-flex justify-content-center">
                            {% if recipe.image %}
                                <img src="{{ recipe.image.url }}"
                                     alt="{{ recipe.name }}"
                                     class="img-fluid rounded shadow">
                            {% else %}
                                <img src="https://placehold.co/800?text=placeholder&font=roboto"
                                     alt="{{ recipe.name }}"
                                     class="img-fluid rounded shadow">
                            {% endif %}
                        </div>
                        <div class="col-md-8 ">
                            <div class="card-body">
                                <h5 class="card-title">{{ recipe.name }}</h5>
                                <p>Description:</p>
                                <p class="card-text">{{ recipe.description }}</p>
                                <p class="card-text">
                                    <small class="text-body-secondary"><i>added: {{ recipe.date_added|date:"M d, Y " }} </i></small>
                                </p>
                                <small> <a href="{% url "recipes:recipe_detail" recipe.id %}">View recipe details</a> </small>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>You have not added any recipes to your cookbook yet.</p>
    {% endif %}
{% endblock content %}

recipes/templates/recipes/recipe.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
    {% if recipe %}
        <div class="card mb-3 mx-auto">
            <div class="row g-0">
                <div class="col-md-4 d-flex justify-content-center">
                    {% if recipe.image %}
                        <img src="{{ recipe.image.url }}"
                             alt="{{ recipe.name }}"
                             class="card-img-top img-fluid rounded shadow">
                    {% else %}
                        <img src="https://placehold.co/800?text=placeholder&font=roboto"
                             alt="{{ recipe.name }}"
                             class="img-fluid rounded shadow">
                    {% endif %}
                </div>
                <div class="col-md-8 ">
                    <div class="card-body">
                        <h5 class="card-title">{{ recipe.name }}</h5>
                        <p>Description:</p>
                        <p class="card-text">{{ recipe.description }}</p>
                        Ingredients:
                        <p class="card-text">{{ recipe.ingredients }}</p>
                        Directions:
                        <p class="card-text">{{ recipe.directions }}</p>
                        <p class="card-text">
                            <small class="text-body-secondary"><i>added: {{ recipe.date_added|date:"M d, Y " }} </i></small>
                        </p>
                        <div class="card-text">
                            <form action="{% url "recipes:toggle_favorite" recipe_id=recipe.id %}"
                                  method="post">
                                {% csrf_token %}
                                {% if recipe in user.favorite_recipes.all %}
                                    <button type="submit" class="btn btn-link p-0 m-0">
                                        <i class="fas fa-heart" style="color:red"></i>
                                    </button>
                                {% else %}
                                    <button type="submit" class="btn btn-link p-0 m-0">
                                        <i class="far fa-heart"></i>
                                    </button>
                                {% endif %}
                            </form>
                        <a href="{% url "recipes:delete_recipe" recipe.id %}"><i class="fa fa-trash" aria-hidden="true"></i>
                    </a>
                    <a class="p-3" href="{% url "recipes:edit_recipe" recipe.id %}"> <i class="fas fa-edit"></i></a>
                </div>
                {% comment %} <small> <a href="{% url "recipes:recipe_detail" recipe.id %}">View recipe details</a> </small> {% endcomment %}
            </div>
        </div>
    </div>
</div>
{% else %}
<p>No recipe found.</p>
{% endif %}
<div class="mt-4">
    <h5>Comments:</h5>
    {% for comment in comments %}
        <div class="border p-3 mb-3 rounded">
            <div class="d-flex align-items-center mb-2">
                {% if comment.user.profile.profile_photo %}
                    <img src="{{ comment.user.profile.profile_photo.url }}"
                         alt="Profile"
                         class="rounded-circle me-2"
                         style="width: 40px;
                                height: 40px">
                {% endif %}
                <div>
                    <strong>{{ comment.user.username }}</strong>
                    commented on {{ comment.date_added|date:"F d, Y" }}
                    at {{ comment.date_added|time:"H:i" }}:
                    <br>
                    <p class="fst-italic">{{ comment.text }}</p>
                </div>
            </div>
        </div>
    {% empty %}
        <p>No comments yet.</p>
    {% endfor %}
</div>
<!-- Comment Form -->
{% if user.is_authenticated %}
    <div class="mt-4">
        <h5>Leave a comment:</h5>
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form comment_form %}
            <div class="mt-3">{% bootstrap_button button_type="submit" content="Post Comment" %}</div>
        </form>
    </div>
{% else %}
    <p>
        <a href="{% url "accounts:login" %}">Log in</a> to post a comment
    </p>
{% endif %}
{% endblock content %}

recipes/templates/recipes/recipe_confirmation_delete.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="container mt-4">
        <h2>Are you sure you want to delete "{{ recipe.name }}"?</h2>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Yes, delete</button>
            <a href="{% url "recipes:recipe_detail" recipe.id %}">Cancel</a>
        </form>
    </div>
{% endblock content %}

recipes/templates/recipes/recipe_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="container mt-4">
        <h3>Edit Recipe</h3>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Save changes</button>
        </form>
    </div>
{% endblock content %}

recipes/templates/recipes/recipes.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block page_header %}
    <h3>Recipes</h3>
{% endblock page_header %}
{% block content %}
    <div>
        {% for recipe in recipes %}
            <div class="card mb-3 mx-auto" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-4 d-flex justify-content-center">
                        {% if recipe.image %}
                            <img src="{{ recipe.image.url }}"
                                 alt="{{ recipe.name }}"
                                 class="img-fluid rounded shadow">
                        {% else %}
                            <img src="https://placehold.co/800?text=placeholder&font=roboto"
                                 alt="{{ recipe.name }}"
                                 class="img-fluid rounded shadow">
                        {% endif %}
                    </div>
                    <div class="col-md-8 ">
                        <div class="card-body">
                            <h5 class="card-title">{{ recipe.name }}</h5>
                            <p>Description:</p>
                            <p class="card-text">{{ recipe.description }}</p>
                            <p class="card-text">
                                <small class="text-body-secondary"><i>added: {{ recipe.date_added|date:"M d, Y " }} </i></small>
                            </p>
                            <small> <a href="{% url "recipes:recipe_detail" recipe.id %}">View recipe details</a> </small>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

recipes/templates/recipes/search_results.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block page_header %}
    <h3>Recipes</h3>
{% endblock page_header %}
{% block content %}
    <div class="container mt-4">
        {% if results %}
            {% for recipe in results %}
                <div class="card mb-3 mx-auto" style="max-width: 540px;">
                    <div class="row g-0">
                        <div class="col-md-4 d-flex justify-content-center">
                            {% if recipe.image %}
                                <img src="{{ recipe.image.url }}"
                                     alt="{{ recipe.name }}"
                                     class="img-fluid rounded shadow">
                            {% else %}
                                <img src="https://placehold.co/800?text=placeholder&font=roboto"
                                     alt="{{ recipe.name }}"
                                     class="img-fluid rounded shadow">
                            {% endif %}
                        </div>
                        <div class="col-md-8 ">
                            <div class="card-body">
                                <h5 class="card-title">{{ recipe.name }}</h5>
                                <p>Description:</p>
                                <p class="card-text">{{ recipe.description }}</p>
                                <p class="card-text">
                                    <small class="text-body-secondary"><i>added: {{ recipe.date_added|date:"M d, Y " }} </i></small>
                                </p>
                                <small> <a href="{% url "recipes:recipe_detail" recipe.id %}">View recipe details</a> </small>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>No recipes found for "{{ query }}".</p>
        {% endif %}
    </div>
{% endblock content %}