foodie/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("sandbox/", include("sandbox.urls")),
    path("", include("foodie_app.urls")),
    path("recipes/", include("recipes.urls")),
    path("comments/", include("comments.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from recipes import views


app_name = "recipes"

router = DefaultRouter()
router.register(r"recipes", views.RecipeViewSet, basename="recipe")

urlpatterns = [
    path("", views.recipes, name="index"),
    path("<int:recipe_id>", views.recipe_detail, name="recipe_detail"),
    path(
        "<int:recipe_id>/toggle_favorite", views.toggle_favorite, name="toggle_favorite"
    ),
    path("my-favorites/", views.favorite_recipes, name="favorite_recipes"),
    path("search/", views.search_results, name="search_results"),
    path("<int:recipe_id>/delete/", views.delete_recipe, name="delete_recipe"),
    path("<int:recipe_id>/edit/", views.edit_recipe, name="edit_recipe"),
    path("api/", include(router.urls)),
]

sandbox/urls.py
from django.urls import path
from . import views

app_name = "sandbox"
# https://mysite.com/
urlpatterns = [
    path("", views.index, name="index"),
    path("recipes/", views.RecipeListView.as_view(), name="recipe_list"),
    path("recipes/<int:pk>", views.RecipeDetailView.as_view(), name="recipe_detail"),
    path("refreshing/", views.SpecifcRecipesView.as_view(), name="refreshing_recipes"),
    path("feedback/", views.feedback, name="feedback"),
    path("feedback/review", views.feedback_review, name="feedback_review"),
    path("thank-you/", views.thank_you, name="thank_you"),
]

sandbox/models.py
from django.db import models


class Feedback(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    feedback = models.TextField()
    satisfaction = models.CharField(max_length=10)

    def __str__(self):
        return self.name

sandbox/forms.py
from django import forms

choices = [("happy", "Happy"), ("neutral", "Neutral"), ("sad", "Sad")]


class FeedbackForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    feedback = forms.CharField()
    satisfaction = forms.ChoiceField(choices=choices, widget=forms.RadioSelect)

    def clean_email(self):
        email = self.cleaned_data["email"]
        if "@gmail.com" not in email:
            raise forms.ValidationError("Please user your gmail email")
        return email

sandbox/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import ListView, DetailView, View

from recipes.models import Recipe, Category
from sandbox.forms import FeedbackForm
from sandbox.models import Feedback
from django.contrib import messages


# Create your views here.
def index(request):

    recipes = Recipe.objects.all()
    context = {"recipes": recipes}
    return render(request, "sandbox/index.html", context)


class RecipeListView(ListView):
    model = Recipe
    template_name = "sandbox/index.html"

    context_object_name = "recipes"

    def get_queryset(self):
        filtered_recipes = Recipe.objects.filter(category__name__iexact="soup")
        return filtered_recipes


class RecipeDetailView(DetailView):
    model = Recipe
    template_name = "sandbox/recipe_detail.html"
    context_object_name = "recipe"


def thank_you(request):
    return HttpResponse("Thank you for your feedback.")


def feedback(request):
    request.session["feedback_visits"] = request.session.get("feedback_visits", 0) + 1

    if request.method == "POST":
        form = FeedbackForm(request.POST)
        if form.is_valid():

            # save form data to session
            request.session["feedback_data"] = form.cleaned_data
            return redirect("sandbox:feedback_review")

            # name = form.cleaned_data["name"]
            # email = form.cleaned_data["email"]
            # feedback = form.cleaned_data["feedback"]
            # satisfaction = form.cleaned_data["satisfaction"]
            # Feedback.objects.create(
            #     name=name, email=email, feedback=feedback, satisfaction=satisfaction
            # )
            # messages.add_message(
            #     request, messages.SUCCESS, "Feedback sent successfully!"
            # )
            # messages.success(request, "Feedback sent successfully!")

            # return redirect("sandbox:index")

    else:
        form = FeedbackForm()

    context = {"form": form, "visits": request.session["feedback_visits"]}
    return render(request, "sandbox/feedback_form.html", context)


def feedback_review(request):
    feedback_data = request.session.get("feedback_data", {})
    if request.method == "POST":
        Feedback.objects.create(**feedback_data)
        del request.session["feedback_data"]
        return redirect("sandbox:index")

    form = FeedbackForm(initial=feedback_data)
    return render(request, "sandbox/feedback_review.html", {"form": form})


class SpecifcRecipesView(View):
    def get(self, request, *args, **kwargs):
        # fetch recipes with "refreshing" in the description
        refreshing_recipes = Recipe.objects.filter(description__icontains="rich")
        context = {"refreshing": refreshing_recipes}
        return render(request, "sandbox/refreshing_recipes.html", context)

sandbox/templates/sandbox/feedback_form.html
{% extends "base.html" %}
{% block content %}
    {% if visits %}<p>You have visited this page {{ visits }} time{{ visits|pluralize }}</p>{% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock content %}

sandbox/templates/sandbox/feedback_review.html
{% extends "base.html" %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Confirm submission</button>
    </form>
{% endblock content %}

sandbox/templates/sandbox/index.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button"
                            class="btn-close"
                            data-bs-dismiss="alert"
                            aria-label="Close"></button>
                </div>
            {% endfor %}
        </div>
    {% endif %}
    {% if recipes %}
        <ul>
            {% for recipe in recipes %}
                <li>
                    <a href="{% url "sandbox:recipe_detail" recipe.id %}">{{ recipe.name }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No foods found.</p>
    {% endif %}
{% endblock content %}

sandbox/templates/sandbox/recipe_detail.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
    {% if recipe %}
        <div class="card mb-3 mx-auto" style="max-width: 540px;">
            <div class="row g-0">
                <div class="col-md-4 d-flex justify-content-center">
                    {% if recipe.image %}
                        <img src="{{ recipe.image.url }}"
                             alt="{{ recipe.name }}"
                             class="img-fluid rounded shadow">
                    {% else %}
                        <img src="https://placehold.co/800?text=placeholder&font=roboto"
                             alt="{{ recipe.name }}"
                             class="img-fluid rounded shadow">
                    {% endif %}
                </div>
                <div class="col-md-8 ">
                    <div class="card-body">
                        <h5 class="card-title">{{ recipe.name }}</h5>
                        <p>Description:</p>
                        <p class="card-text">{{ recipe.description }}</p>
                        Ingredients:
                        <p class="card-text">{{ recipe.ingredients }}</p>
                        Directions:
                        <p class="card-text">{{ recipe.directions }}</p>
                        <p class="card-text">
                            <small class="text-body-secondary"><i>added: {{ recipe.date_added|date:"M d, Y " }} </i></small>
                        </p>
                        <small> <a href="{% url "recipes:recipe_detail" recipe.id %}">View recipe details</a> </small>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <p>No recipe found.</p>
    {% endif %}
{% endblock content %}

sandbox/templates/sandbox/refreshing_recipes.html
{% extends "base.html" %}
{% block content %}
    {% if refreshing %}
        <ul>
            {% for recipe in refreshing %}
                <li>
                    <a href="{% url "sandbox:recipe_detail" recipe.id %}">{{ recipe.name }}</a>
                    Description:
                    <pre>{{recipe.description}} </pre>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No foods found.</p>
    {% endif %}
{% endblock content %}