foodie/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("sandbox/", include("sandbox.urls")),
    path("", include("foodie_app.urls")),
    path("recipes/", include("recipes.urls")),
    path("comments/", include("comments.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodie_app/urls.py
from django.urls import path
from . import views

app_name = "foodie_app"
urlpatterns = [
    path("", views.index, name="index"),
    path("recipes/<int:category_id>/", views.recipes, name="recipes"),
    path("add-category/", views.add_category, name="add_category"),
    path("add_recipe/", views.add_recipe, name="add_recipe_no_genre"),
    path(
        "add_recipe/category/<int:category_id>/",
        views.add_recipe,
        name="add_recipe_with_genre",
    ),
]

recipes/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from recipes import views


app_name = "recipes"

router = DefaultRouter()
router.register(r"recipes", views.RecipeViewSet, basename="recipe")

urlpatterns = [
    path("", views.recipes, name="index"),
    path("<int:recipe_id>", views.recipe_detail, name="recipe_detail"),
    path(
        "<int:recipe_id>/toggle_favorite", views.toggle_favorite, name="toggle_favorite"
    ),
    path("my-favorites/", views.favorite_recipes, name="favorite_recipes"),
    path("search/", views.search_results, name="search_results"),
    path("<int:recipe_id>/delete/", views.delete_recipe, name="delete_recipe"),
    path("<int:recipe_id>/edit/", views.edit_recipe, name="edit_recipe"),
    path("api/", include(router.urls)),
]

foodie_app/models.py
from django.db import models


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ["-date_added"]
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

recipes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from foodie_app.models import Category


# Create your models here.
class Recipe(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    ingredients = models.TextField()
    directions = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, related_name="recipes"
    )
    image = models.ImageField(upload_to="recipe_images/", null=True, blank=True)
    favorited_by = models.ManyToManyField(User, related_name="favorite_recipes", blank=True)
    
    def get_absolute_url(self):
        return reverse("recipes:recipe_detail", args=[str(self.id)])

    def __str__(self):
        return self.name

foodie_app/forms.py
from django import forms

from foodie_app.models import Category
from recipes.models import Recipe


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["name"]
        # labels = {"name": "Category Name"}
        widgets = {
            "name": forms.TextInput(
                attrs={
                    "placeholder": "Category name",
                }
            )
        }


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = [
            "name",
            "description",
            "ingredients",
            "directions",
            "category",
            "image",
        ]
        widgets = {
            "name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Recipe title"}
            ),
            "description": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "placeholder": "Description",
                    "rows": "5",
                }
            ),
            "ingredients": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "placeholder": "Ingredients",
                    "rows": "5",
                }
            ),
            "category": forms.Select(attrs={"class": "form-select"}),
        }

recipes/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField(
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search recipes...", "class": "form-control mr-sm-2"}
        ),
    )

foodie_app/views.py
from django.shortcuts import get_object_or_404, redirect, render

from foodie_app.forms import CategoryForm, RecipeForm
from .models import Category
from recipes.models import Recipe
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    categories = Category.objects.all()
    context = {"categories": categories}

    return render(request, "foodie_app/index.html", context)


def recipes(request, category_id):
    recipes = Recipe.objects.filter(category=category_id).order_by("-date_added")
    category = Category.objects.get(pk=category_id)

    context = {"recipes": recipes, "category": category}
    return render(request, "foodie_app/recipes.html", context)


@login_required
def add_category(request):
    if request.method == "POST":

        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("foodie_app:index")
        else:
            return render(request, "foodie_app/add_category.html", context)
    else:
        form = CategoryForm()
        context = {"form": form}

        return render(request, "foodie_app/add_category.html", context)


@login_required
def add_recipe(request, category_id=None):
    category = None
    initial_data = {}

    if category_id:
        category = get_object_or_404(Category, id=category_id)
        initial_data = {"category": category}

    if request.method == "POST":
        form = RecipeForm(request.POST, request.FILES, initial=initial_data)
        if form.is_valid():
            new_recipe = form.save(commit=False)
            new_recipe.user = request.user
            new_recipe.save()
            return redirect("foodie_app:recipes", category_id=new_recipe.category.id)
    else:
        form = RecipeForm(initial=initial_data)

    context = {"form": form, "category": category}
    return render(request, "foodie_app/add_recipe.html", context)

recipes/views.py
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from comments.forms import CommentForm
from foodie_app.forms import RecipeForm
from recipes.serializers import RecipeSerializer
from .models import Recipe
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from rest_framework import viewsets


def recipes(request):

    recipes = Recipe.objects.all().order_by("-date_added")
    context = {"recipes": recipes}

    return render(request, "recipes/recipes.html", context)


def recipe_detail(request, recipe_id):

    # recipe = Recipe.objects.get(id=recipe_id)
    recipe = get_object_or_404(Recipe, id=recipe_id)
    comments = recipe.comments.all()

    new_comment = None

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.recipe = recipe
            new_comment.user = request.user
            new_comment.save()
            return redirect(
                recipe.get_absolute_url()
            )  # Redirect to the same recipe page - refresh
    else:
        comment_form = CommentForm()

    context = {"recipe": recipe, "comments": comments, "comment_form": comment_form}
    return render(request, "recipes/recipe.html", context)


@login_required
def toggle_favorite(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)

    if request.user in recipe.favorited_by.all():
        recipe.favorited_by.remove(request.user)
    else:
        recipe.favorited_by.add(request.user)
    return redirect("recipes:recipe_detail", recipe_id=recipe_id)


@login_required
def favorite_recipes(request):
    user = request.user
    favorites = user.favorite_recipes.all()
    context = {"recipes": favorites}
    return render(request, "recipes/favorite_recipes.html", context)


def search_results(request):
    query = request.GET.get("query", "")

    results = (
        Recipe.objects.filter(
            Q(name__icontains=query)
            | Q(description__icontains=query)
            | Q(ingredients__icontains=query)
            | Q(directions__icontains=query)
            | Q(category__name__icontains=query)
        ).distinct()
        if query
        else []
    )
    # avoid duplicate results
    # seen_ids = set()
    # unique_results = []
    # for result in results:
    #     if result.id not in seen_ids:
    #         unique_results.append(result)
    #         seen_ids.add(result.id)

    # else:
    #     unique_results = []

    # results = Recipe.objects.filter(name__icontains=query) if query else []

    context = {"query": query, "results": results}
    return render(request, "recipes/search_results.html", context)


@login_required
def delete_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)

    # check if the current user is the owner of the recipe or a superuser
    if not request.user == recipe.user and not request.user.is_superuser:
        return HttpResponseForbidden()

    if request.method == "POST":
        recipe.delete()
        return redirect("recipes:index")

    context = {"recipe": recipe}
    return render(request, "recipes/recipe_confirmation_delete.html", context)


@login_required
def edit_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)

    if not request.user == recipe.user and not request.user.is_superuser:
        return HttpResponse("Not allowed.")
        # return HttpResponseForbidden()

    if request.method == "POST":
        form = RecipeForm(request.POST, request.FILES, instance=recipe)
        if form.is_valid():
            form.save()
            return redirect("recipes:recipe_detail", recipe_id=recipe.id)
    else:
        form = RecipeForm(instance=recipe)

    context = {"form": form, "recipe": recipe}
    return render(request, "recipes/recipe_form.html", context)


class RecipeViewSet(viewsets.ModelViewSet):
    queryset = Recipe.objects.all()
    serializer_class = RecipeSerializer

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

foodie_app/templates/foodie_app/add_category.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block page_header %}
    <h3>Add Category</h3>
{% endblock page_header %}
{% block content %}
    <div>
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% bootstrap_button button_type="submit" content="Save Category" %}
        </form>
    </div>
{% endblock content %}

foodie_app/templates/foodie_app/add_recipe.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block page_header %}
    <h2>Add a new Recipe</h2>
    {% if category %}to {{ category.name }}{% endif %}
{% endblock page_header %}
{% block content %}
    {% comment %} <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Recipe</button>
    </form> {% endcomment %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Save Recipe" %}
    </form>
</div>
{% endblock content %}

foodie_app/templates/foodie_app/index.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="container">
        <div class="col-md-12">
            <h3 class="display-4">Foodie</h3>
            <p class="lead">
                Foodie is a web application that allows you to search for recipes based on the ingredients you have in your kitchen.
                You can also save your favorite recipes and create a shopping list for the ingredients you need to buy.
            </p>
        </div>
    </div>
    <div class="container">
        <h6 class="display-5">Trending Recipe Categories</h6>
        <a href="{% url "foodie_app:add_category" %}">Add Category</a>
    </div>
    <div class="container mt-4">
        <div class="row">
            {% for category in categories %}
                <div class="col-sm-6 col-md-4 col-lg-3 mb-4">
                    <div class="card h-100  text-bg-light mb-3">
                        <a class="card-title" href="{% url "foodie_app:recipes" category.id %}">
                            <div class="card-body">{{ category }}</div>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

foodie_app/templates/foodie_app/recipes.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block page_header %}
    <h3>
        Recipes under <i>{{ category }} </i>
    </h3>
{% endblock page_header %}
{% block content %}
    <a href="{% url "foodie_app:add_recipe_with_genre" category_id=category.id %}">Add Recipe</a>
    <div>
        {% for recipe in recipes %}
            {% comment %} <div class="card mb-3">
                <h6 class="card-header">
                    {{ recipe.name }}, <i>added: {{ recipe.date_added|date:"M d, Y " }} </i>
                </h6>
                <div class="card-body">
                    {% if recipe.image %}
                        <img width="100" height="100" src="{{ recipe.image.url }}" alt="{{ recipe.name }}">
                    {% endif %}
                    <p>Description:</p>
                    {{ recipe.description }}
                    <div class="row align-items-center mt-3">
                        <div class="col">
                            <small> <a href="{% url "recipes:recipe_detail" recipe.id %}">View recipe details</a> </small>
                        </div>
                        <div class="col-auto">
                            {% if recipe.user.profile.profile_photo %}
                                <img src="{{ recipe.user.profile.profile_photo.url }}" alt="Profile photo" class="rounded-circle" widht="30" height="30">
                            {% endif %}
                            <small>Created by: {{ recipe.user.username }}</small>
                        </div>
                    </div>
                </div>
            </div> {% endcomment %}
            <div class="card mb-3 mx-auto" style="max-width: 540px;">
                <div class="row g-0 ">
                    <div class="col-md-4 d-flex justify-content-center">
                        {% if recipe.image %}
                            <img src="{{ recipe.image.url }}"
                                 alt="{{ recipe.name }}"
                                 class="img-fluid rounded shadow center">
                        {% else %}
                            <img src="https://placehold.co/800?text=placeholder&font=roboto"
                                 alt="{{ recipe.name }}"
                                 class="img-fluid rounded shadow">
                        {% endif %}
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{ recipe.name }}</h5>
                            <p>Description:</p>
                            <p class="card-text">{{ recipe.description }}</p>
                            <p class="card-text">
                                <small class="text-body-secondary"><i>added: {{ recipe.date_added|date:"M d, Y " }} </i></small>
                            </p>
                        </div>
                        <div class="row align-items-center mt-3 p-3">
                            <div class="col">
                                <small> <a href="{% url "recipes:recipe_detail" recipe.id %}">View recipe details</a> </small>
                            </div>
                            <div class="col-auto">
                                {% if recipe.user.profile.profile_photo %}
                                    <img src="{{ recipe.user.profile.profile_photo.url }}"
                                         alt="Profile photo"
                                         class="rounded-circle"
                                         widht="30"
                                         height="30">
                                {% endif %}
                                <small>Created by: {{ recipe.user.username }}</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}