accounts/urls.py
from django.urls import path, include
from .views import register
from accounts import views

app_name = "accounts"
urlpatterns = [
    path("register/", register, name="register"),
    path("", include("django.contrib.auth.urls")),
    path("edit-profile/", views.edit_user_profile, name="edit_user_profile"),
]

foodie/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("sandbox/", include("sandbox.urls")),
    path("", include("foodie_app.urls")),
    path("recipes/", include("recipes.urls")),
    path("comments/", include("comments.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodie_app/urls.py
from django.urls import path
from . import views

app_name = "foodie_app"
urlpatterns = [
    path("", views.index, name="index"),
    path("recipes/<int:category_id>/", views.recipes, name="recipes"),
    path("add-category/", views.add_category, name="add_category"),
    path("add_recipe/", views.add_recipe, name="add_recipe_no_genre"),
    path(
        "add_recipe/category/<int:category_id>/",
        views.add_recipe,
        name="add_recipe_with_genre",
    ),
]

recipes/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from recipes import views


app_name = "recipes"

router = DefaultRouter()
router.register(r"recipes", views.RecipeViewSet, basename="recipe")

urlpatterns = [
    path("", views.recipes, name="index"),
    path("<int:recipe_id>", views.recipe_detail, name="recipe_detail"),
    path(
        "<int:recipe_id>/toggle_favorite", views.toggle_favorite, name="toggle_favorite"
    ),
    path("my-favorites/", views.favorite_recipes, name="favorite_recipes"),
    path("search/", views.search_results, name="search_results"),
    path("<int:recipe_id>/delete/", views.delete_recipe, name="delete_recipe"),
    path("<int:recipe_id>/edit/", views.edit_recipe, name="edit_recipe"),
    path("api/", include(router.urls)),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% load django_bootstrap5 %}
        {% load static %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
        <link href="{% static 'fontawesomefree/css/all.min.css' %}"
              rel="stylesheet"
              type="text/css">
        <title>Foodie</title>
        <body>
            <nav class="navbar navbar-expand-lg bg-body-tertiary">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url "foodie_app:index" %}">Foodie <i class="fa-solid fa-bowl-food"></i></a>
                    <button class="navbar-toggler"
                            type="button"
                            data-bs-toggle="collapse"
                            data-bs-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent"
                            aria-expanded="false"
                            aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link btn btn-outline-success m-2"
                                   aria-current="page"
                                   href="{% url "foodie_app:add_recipe_no_genre" %}">Add Recipe</a>
                            </li>
                            <li class="nav-item ">
                                <a class="nav-link btn btn-outline-success m-2"
                                   aria-current="page"
                                   href="{% url "recipes:index" %}">All Recipes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link btn btn-outline-success m-2 "
                                   aria-current="page"
                                   href="{% url "recipes:favorite_recipes" %}">My Cookbook <i class="fa-solid fa-heart"></i></a>
                            </li>
                            <li class="nav-item">
                                <form class="d-flex my-2 my-lg-0 m-2 p-2"
                                      action="{% url "recipes:search_results" %}"
                                      method="get">
                                    {{ search_form.query }}
                                    <button class="btn btn-outline-success my-2 my-sm-0 m-1" type="submit">Search</button>
                                </form>
                            </li>
                        </ul>
                        <!-- Right Side Of Navbar -->
                        <ul class="navbar-nav ms-auto mb-2 mb-md-0">
                            <!-- Authentication Links -->
                            {% if user.is_authenticated %}
                                <li class="nav-item d-flex align-items-center">
                                    {% if user.profile.profile_photo %}
                                        <img src="{{ user.profile.profile_photo.url }}"
                                             alt="Profile"
                                             style="width: 30px;
                                                    height: 30px;
                                                    border-radius: 50%;
                                                    margin-right: 5px">
                                    {% endif %}
                                    <span class="nav-text me-2">Welcome, <a href="{% url "accounts:edit_user_profile" %}">{{ user.username }}</a></span>
                                </li>
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url "accounts:register" %}">Register</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url "accounts:login" %}">Login</a>
                                </li>
                            {% endif %}
                        </ul>
                        <!-- End of account related links -->
                        {% if user.is_authenticated %}
                            <form action="{% url 'accounts:logout' %}" method='post'>
                                {% csrf_token %}
                                <button type="submit" class="btn btn-outline-secondary btn-sm">Logout</button>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </nav>
            <!-- End of Navbar -->
            <main class="container">
                <div class="pb-2 mb-2 border-bottom">
                    {% block page_header %}
                    {% endblock page_header %}
                </div>
                {% block content %}
                {% endblock content %}
            </main>
            <footer class="footer mt-auto py-3 bg-light mx-auto">
                <div class="container">
                    <span class="text-muted">© 2029 Foodie - All Rights Reserved</span>
                </div>
            </footer>
        </body>
    </html>